/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Primary brand — Orange #E8510A (constant across modes)
        brand: {
          DEFAULT: '#E8510A',
          50:  '#FEF3EC',
          100: '#FCE3D0',
          200: '#F9C7A2',
          300: '#F5A26B',
          400: '#F07E38',
          500: '#E8510A',
          600: '#C44508',
          700: '#9A3806',
          800: '#6E2A06',
          900: '#451D06',
          950: '#2A1003',
        },
        // Secondary brand — Green #5A9E28 (constant across modes)
        green: {
          DEFAULT: '#5A9E28',
          50:  '#F4F9EE',
          100: '#E5F0D6',
          200: '#CBE2AE',
          300: '#ACCF82',
          400: '#82B852',
          500: '#5A9E28',
          600: '#48801F',
          700: '#386417',
          800: '#2A4A13',
          900: '#1B320C',
          950: '#101E07',
        },
        // Growth accent — green via CSS var (used across the codebase as text-growth etc.)
        growth: {
          DEFAULT: 'var(--growth)',
          50:  '#F4F9EE',
          100: '#E5F0D6',
          200: '#CBE2AE',
          300: '#ACCF82',
          400: '#82B852',
          500: '#5A9E28',
          600: 'var(--growth-strong)',
          700: '#386417',
          800: '#2A4A13',
          900: '#1B320C',
          950: '#101E07',
        },
        // Semantic tokens — resolve through CSS variables
        background:       'var(--bg)',
        foreground:       'var(--text)',
        bgalt:            'var(--bg-alt)',
        card:             'var(--card-bg)',
        'card-foreground':'var(--text)',
        'card-border':    'var(--card-border)',
        popover:          'var(--card-bg)',
        'popover-foreground': 'var(--text)',
        muted:            'var(--bg-alt)',
        'muted-foreground':'var(--text-muted)',
        accent:           'var(--bg-alt)',
        'accent-foreground':'var(--text)',
        nav:              'var(--nav-bg)',
        charcoal:         'var(--charcoal)',
        charcoaldeep:     'var(--charcoal-deep)',
        navy:             'var(--navy)',
        navydeep:         'var(--navy-deep)',
        'navy-soft':      'var(--navy-soft)',
        footer:           'var(--footer-bg)',
        border:           'var(--card-border)',
        input:            'var(--card-border)',
        ring:             'var(--brand)',
        primary: {
          DEFAULT:    'var(--brand)',
          foreground: '#FFFFFF',
        },
        secondary: {
          DEFAULT:    'var(--growth)',
          foreground: '#FFFFFF',
        },
        destructive: {
          DEFAULT:    'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        // Dark neutrals (kept for admin/legacy components)
        ink: {
          DEFAULT: '#1C1C1E',
          950: '#0A0A0A',
          900: '#111111',
          800: '#1C1C1E',
          700: '#2C2C2E',
          600: '#3A3A3C',
          500: '#636366',
          400: '#8E8E93',
          300: '#AEAEB2',
          200: '#C7C7CC',
          100: '#D1D1D6',
          50:  '#E5E5EA',
          25:  '#F2F2F7',
        },
      },
      fontFamily: {
        sans:    ['var(--font-inter)', 'system-ui', 'sans-serif'],
        body:    ['var(--font-inter)', 'system-ui', 'sans-serif'],
        heading: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        nav:     ['var(--font-playfair)', 'Georgia', 'serif'],
        display: ['var(--font-playfair)', 'Georgia', 'serif'],
        mono:    ['var(--font-jetbrains)', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'h1': ['clamp(2.25rem, 4.5vw, 4rem)', { lineHeight: '1.08', letterSpacing: '-0.02em' }],
        'h2': ['clamp(1.75rem, 3vw, 2.625rem)', { lineHeight: '1.2', letterSpacing: '-0.015em' }],
        'h3': ['clamp(1.375rem, 2vw, 1.75rem)', { lineHeight: '1.3' }],
      },
      borderRadius: {
        lg:  'var(--radius)',
        md:  'calc(var(--radius) - 2px)',
        sm:  'calc(var(--radius) - 4px)',
        btn: 'var(--radius-button)',
        badge: 'var(--radius-badge)',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      boxShadow: {
        brand:        '0 2px 8px rgba(232,81,10,0.28)',
        'brand-lg':   '0 6px 24px rgba(232,81,10,0.35)',
        'brand-glow': '0 0 40px -6px rgba(232,81,10,0.40)',
        'brand-sm':   '0 0 20px -4px rgba(232,81,10,0.30)',
        card:         'var(--card-shadow)',
        'card-hover': 'var(--card-shadow-hover)',
        'card-dark':  '0 1px 8px rgba(0,0,0,0.30), 0 4px 20px rgba(0,0,0,0.25)',
        soft:         '0 2px 20px -2px rgba(0,0,0,0.06)',
        'soft-md':    '0 4px 30px -4px rgba(0,0,0,0.10)',
        'soft-lg':    '0 8px 40px -4px rgba(0,0,0,0.12)',
        'soft-xl':    '0 16px 60px -8px rgba(0,0,0,0.16)',
      },
      keyframes: {
        'fade-up': {
          '0%':   { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          '0%':   { opacity: '0', transform: 'translateX(28px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-left': {
          '0%':   { opacity: '0', transform: 'translateX(-28px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-in': {
          '0%':   { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-8px)' },
        },
        'pulse-ring': {
          '0%':   { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(90,158,40,0.5)' },
          '70%':  { transform: 'scale(1)',    boxShadow: '0 0 0 12px rgba(90,158,40,0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(90,158,40,0)' },
        },
        'chat-in': {
          '0%':   { opacity: '0', transform: 'translateY(16px) scale(0.97)' },
          '100%': { opacity: '1', transform: 'translateY(0)   scale(1)' },
        },
        'shimmer': {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200%  0' },
        },
      },
      animation: {
        'fade-up':        'fade-up 0.35s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.6s ease-out forwards',
        'slide-in-left':  'slide-in-left 0.6s ease-out forwards',
        'scale-in':       'scale-in 0.55s ease-out forwards',
        'float':          'float 5s ease-in-out infinite',
        'pulse-ring':     'pulse-ring 2s cubic-bezier(0.455,0.03,0.515,0.955) infinite',
        'chat-in':        'chat-in 0.3s ease-out forwards',
        'shimmer':        'shimmer 3s linear infinite',
      },
    },
  },
  plugins: [],
};
