-- Email template content enhancements to reduce spam scores.
-- Updates template bodies with substantial, human-readable content.
begin;

-- health_check_report_summary
update public.email_templates
set
  subject = 'Your {{check_name}} summary report from Deni Sawa Partners',
  preview_text = 'View your Deni Sawa Partners financial health summary online',
  body_lexical = '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Hello {{recipient_name}},","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Thank you for completing your {{check_name}} with Deni Sawa Partners. We have generated your summary report with key insights on your business financial health.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Your report includes overall financial health score, key strengths and improvement areas, and priority recommendations.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Click the link below to view your report online. You can also download a PDF or Word document version.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[],"direction":"ltr","format":"","indent":0,"href":"{{report_url}}","openInNewTab":true,"style":"display:inline-block;padding:12px 24px;background:#E8510A;color:#ffffff;text-decoration:none;border-radius:4px;font-weight:bold;","text":"View Your Report","type":"link","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"If you did not request this report, please ignore this email or contact us at advisory@denisawa.co.ke.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}',
  body_html = '<p>Hello {{recipient_name}},</p><p>Thank you for completing your <strong>{{check_name}}</strong> with Deni Sawa Partners. We have generated your summary report with key insights on your business financial health.</p><p>Your report includes overall financial health score, key strengths and improvement areas, and priority recommendations.</p><p>Click the link below to view your report online. You can also download a PDF or Word document version.</p><p><a href="{{report_url}}" style="display:inline-block;padding:12px 24px;background:#E8510A;color:#ffffff;text-decoration:none;border-radius:4px;">View Your Report</a></p><p>If you did not request this report, please ignore this email or contact us at advisory@denisawa.co.ke.</p>'
where template_key = 'health_check_report_summary';

-- health_check_report_detailed
update public.email_templates
set
  subject = 'Your {{check_name}} full report from Deni Sawa Partners',
  preview_text = 'Download your detailed Deni Sawa Partners financial health report',
  body_lexical = '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Hello {{recipient_name}},","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"We are pleased to deliver your full {{check_name}} report from Deni Sawa Partners. This comprehensive assessment covers your business financial health, identifying strengths, risks, and actionable recommendations.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Your detailed report includes executive summary of findings, detailed financial ratios and benchmarks, strategic recommendations tailored to your business, and industry comparison data.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Click below to access your full report online.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[],"direction":"ltr","format":"","indent":0,"href":"{{report_url}}","openInNewTab":true,"style":"display:inline-block;padding:12px 24px;background:#E8510A;color:#ffffff;text-decoration:none;border-radius:4px;font-weight:bold;","text":"Access Your Full Report","type":"link","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"If you have questions about your report, our advisory team is available at advisory@denisawa.co.ke.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}',
  body_html = '<p>Hello {{recipient_name}},</p><p>We are pleased to deliver your full <strong>{{check_name}}</strong> report from Deni Sawa Partners. This comprehensive assessment covers your business financial health, identifying strengths, risks, and actionable recommendations.</p><p>Your detailed report includes executive summary of findings, detailed financial ratios and benchmarks, strategic recommendations tailored to your business, and industry comparison data.</p><p>Click below to access your full report online.</p><p><a href="{{report_url}}" style="display:inline-block;padding:12px 24px;background:#E8510A;color:#ffffff;text-decoration:none;border-radius:4px;">Access Your Full Report</a></p><p>If you have questions about your report, our advisory team is available at advisory@denisawa.co.ke.</p>'
where template_key = 'health_check_report_detailed';

-- health_check_started
update public.email_templates
set
  subject = 'You have started your {{check_name}} with Deni Sawa Partners',
  preview_text = 'Continue your financial health assessment where you left off',
  body_lexical = '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Hello {{recipient_name}},","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"You have started your {{check_name}} with Deni Sawa Partners. To complete your assessment and receive your personalized financial health report, resume your session using the link below.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[],"direction":"ltr","format":"","indent":0,"href":"{{resume_url}}","openInNewTab":true,"style":"display:inline-block;padding:12px 24px;background:#E8510A;color:#ffffff;text-decoration:none;border-radius:4px;font-weight:bold;","text":"Resume your assessment","type":"link","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Your progress is saved and will remain available for 7 days. Thank you for choosing Deni Sawa Partners for your financial health assessment.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Questions? Contact us at advisory@denisawa.co.ke.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}',
  body_html = '<p>Hello {{recipient_name}},</p><p>You have started your <strong>{{check_name}}</strong> with Deni Sawa Partners. To complete your assessment and receive your personalized financial health report, resume your session using the link below.</p><p><a href="{{resume_url}}" style="display:inline-block;padding:12px 24px;background:#E8510A;color:#ffffff;text-decoration:none;border-radius:4px;font-weight:bold;">Resume your assessment</a></p><p>Your progress is saved and will remain available for 7 days. Thank you for choosing Deni Sawa Partners for your financial health assessment.</p><p>Questions? Contact us at advisory@denisawa.co.ke.</p>'
where template_key = 'health_check_started';

commit;
