import type { EditorThemeClasses } from 'lexical';

/**
 * Deni Sawa brand theme for Lexical.
 * Colour, typography and node rendering all use the brand tokens.
 */
export const LexicalTheme: EditorThemeClasses = {
  ltr: 'text-left',
  rtl: 'text-right',
  paragraph: 'my-3 leading-[1.7] text-[15px] text-foreground',
  text: {
    base: 'text-foreground',
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline underline-offset-2',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'rounded bg-brand/10 px-1.5 py-0.5 font-mono text-[0.85em] text-brand',
  },
  heading: {
    h1: 'mt-8 mb-3 text-3xl font-semibold tracking-tight text-foreground',
    h2: 'mt-8 mb-3 text-2xl font-semibold tracking-tight text-foreground',
    h3: 'mt-6 mb-2 text-xl font-semibold text-foreground',
    h4: 'mt-5 mb-2 text-lg font-semibold text-foreground',
    h5: 'mt-5 mb-2 text-base font-semibold text-foreground',
    h6: 'mt-5 mb-2 text-base font-semibold text-foreground',
  },
  quote:
    'my-5 border-l-[3px] border-brand bg-brand/5 px-5 py-4 text-[15px] italic leading-relaxed text-foreground',
  list: {
    ul: 'my-4 list-disc space-y-2 pl-6 marker:text-growth',
    ol: 'my-4 list-decimal space-y-2 pl-6 marker:text-brand',
    checklist: 'my-4 list-none space-y-2 pl-2',
    listitem: 'text-[15px] leading-[1.7] text-foreground marker:text-growth',
    listitemChecked: 'line-through text-muted-foreground',
    listitemUnchecked: '',
    nested: {
      listitem: 'list-none',
    },
  },
  code: 'block my-4 overflow-x-auto rounded-lg bg-charcoal p-4 font-mono text-sm text-white',
  codeHighlight: {
    atrule: 'text-brand-300',
    attr: 'text-growth-300',
    boolean: 'text-brand-300',
    builtin: 'text-growth-300',
    cdata: 'text-muted-foreground',
    char: 'text-growth-300',
    class: 'text-brand-300',
    'class-name': 'text-brand-300',
    comment: 'text-muted-foreground italic',
    constant: 'text-brand-300',
    deleted: 'text-red-400',
    doctype: 'text-muted-foreground',
    entity: 'text-brand-300',
    function: 'text-growth-300',
    important: 'text-brand-300',
    inserted: 'text-growth-300',
    keyword: 'text-brand-300',
    namespace: 'text-brand-300',
    number: 'text-brand-300',
    operator: 'text-foreground',
    prolog: 'text-muted-foreground',
    property: 'text-growth-300',
    punctuation: 'text-muted-foreground',
    regex: 'text-brand-300',
    selector: 'text-growth-300',
    string: 'text-growth-300',
    symbol: 'text-brand-300',
    tag: 'text-brand-300',
    url: 'text-brand-300',
    variable: 'text-foreground',
  },
  hashtag: 'text-brand underline underline-offset-2',
  mark: 'bg-brand/15 px-1 py-0.5 text-foreground',
  markOverlap: 'bg-growth/20',
  link: 'text-brand underline underline-offset-2 hover:text-brand-600',
  indent: 'pl-6',
  hr: 'my-6 h-px w-full border-0 bg-gradient-to-r from-transparent via-card-border to-transparent',
  hrSelected: 'outline-2 outline-offset-2 outline-brand',
  table: 'my-6 w-full border-collapse overflow-hidden rounded-lg border border-card-border text-[15px]',
  tableRow: '',
  tableCell: 'border border-card-border bg-card px-4 py-2.5 align-top text-foreground',
  tableCellHeader: 'border border-card-border bg-brand/5 px-4 py-2.5 text-left font-semibold text-foreground',
  tableCellSelected: 'bg-brand/10',
  tableSelected: 'outline-2 outline-offset-2 outline-brand',
  tableSelection: 'bg-brand/15',
  tableScrollableWrapper: 'overflow-x-auto',
  tableAddColumns: 'text-muted-foreground',
  tableAddRows: 'text-muted-foreground',
  tableCellActionButtonContainer: '',
  tableCellActionButton: '',
  tableCellResizer: '',
};
